### ISSUE TITLE
Cant login to Strapi Studio

### ISSUE THREAD

**Issue by Gegham** [wistityhq/strapi#127]
I got this when trying to login:

/Users/geghamharutyunyan/.npm-global/lib/node_modules/strapi/bin/strapi-login.js:100
        } else if (res.statusCode === 400) {
                      ^

TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/Users/geghamharutyunyan/.npm-global/lib/node_modules/strapi/bin/strapi-login.js:100:23)
    at self.callback (/Users/geghamharutyunyan/.npm-global/lib/node_modules/strapi/node_modules/request/request.js:198:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/Users/geghamharutyunyan/.npm-global/lib/node_modules/strapi/node_modules/request/request.js:820:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:306:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)

**Comment by pierreburgy** [comment]
Hi @Gegham,

We have changed our registar, the Studio is going to be accessible within the next 3 hours. Sorry for the trouble.

**Comment by pierreburgy** [comment]
Could you try again now please?

**Comment by Gegham** [comment]
Now it works thanks a lot ! @pierreburgy

**Comment by pierreburgy** [comment]
Alright. I close the issue.

**Comment by dvalvarenga** [comment]
I've the same issue...May I need wait 3 hours to try ? I activated my first strapi account 15 minutes ago...

**Comment by pierreburgy** [comment]
@dvalvarenga, did you receive the activation email and validated your account?
