### ISSUE TITLE
strapi start - Issues

### ISSUE THREAD

**Issue by subu1979** [wistityhq/strapi#133]
Please find the below issues

C:\Users\subu\BCT>strapi start
(node:5536) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
module.js:440
    throw err;
    ^

Error: Cannot find module 'mailcomposer'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\subu\BCT\node_modules\nodemailer\src\nodemailer.js:3:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\subu\BCT\api\email\services\email.js:9:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at C:\Users\subu\BCT\node_modules\strapi\node_modules\include-all\index.js:129:29
    at Array.forEach (native)

C:\Users\subu\BCT>

**Comment by abelsoares** [comment]
What version of node are you using? I believe node 6 is not supported, you need to use node <= 5.
