### ISSUE TITLE
#!/usr/bin/env node --harmony

### ISSUE THREAD

**Issue by sylvainlap** [wistityhq/strapi#4]
I made a fresh install of strapi.

Here is my environment:
```
sylvainlap@CanHardXI:~/DEV/WORKSPACE$ cat /etc/issue
Ubuntu 14.04.3 LTS
```
```
sylvainlap@CanHardXI:~/DEV/WORKSPACE$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
```
```
sylvainlap@CanHardXI:~/DEV/WORKSPACE$ ll /usr/bin/strapi 
lrwxrwxrwx 1 root root 40 oct.   3 11:14 /usr/bin/strapi -> ../lib/node_modules/strapi/bin/strapi.js*
```
But here is the problem:
```
sylvainlap@CanHardXI:~/DEV/WORKSPACE$ strapi new test
/usr/bin/env: node --harmony: Aucun fichier ou dossier de ce type
```

**Comment by loicsaintroch** [comment]
With Node.js v0.12.7 ?

**Comment by sylvainlap** [comment]
yes

**Comment by loicsaintroch** [comment]
All right. I'll look into it this weekend and keep you informed as soon as I have a solution both for Node.js v0.12.x and Node.js v4.

**Comment by sylvainlap** [comment]
You can have a look here: http://stackoverflow.com/questions/24548733/how-to-make-a-nodejs-file-executable-with-harmony-option

**Comment by sylvainlap** [comment]
or here: http://stackoverflow.com/questions/3306518/cannot-pass-an-argument-to-python-with-usr-bin-env-python

**Comment by loicsaintroch** [comment]
I may have found a solution. It's on the `fix/shebang` branch. Steps:

```bash
$ [sudo] npm uninstall strapi -g
$ [sudo] npm cache clear
$ git clone -b fix/shebang git@github.com:wistityhq/strapi.git
$ npm link
```

Can you please try this solution and give me your feedback?

**Comment by mocallu** [comment]
Hey guys, I have same problem. I tried using <code>fix/shebang</code> branch.

Result:

```
mocallu@mocallu-svf-elementary:~/strapi$ strapi login
/usr/local/bin/strapi: 2: /usr/local/bin/strapi: [[: not found
your Strapi email address 

```

It was executed, but with <code>/usr/local/bin/strapi: 2: /usr/local/bin/strapi: [[: not found</code> before.

I'm using node 4.1.1 on Ubuntu 14.04.

**Comment by loicsaintroch** [comment]
Okey, thank you for your feedback @mocallu.

What about you @sylvainlap? Do you still have this issue or you have the same error than @mocallu?

**Comment by sylvainlap** [comment]
Here is my result:
```
sylvainlap@CanHardXI:~/DEV/WORKSPACE$ strapi new test
/usr/bin/strapi: 2: /usr/bin/strapi: [[: not found
info: Your new application `test` is ready at `/home/sylvainlap/DEV/WORKSPACE/test`.
warn: You do not have a `.strapirc` file at `/home/sylvainlap`.
warn: First, you need to create an account on http://dashboard.strapi.io/
warn: Then, execute `$ strapi login` to start the experience.
```

**Comment by loicsaintroch** [comment]
Everything works fine? You just see an error before the logs?

**Comment by sylvainlap** [comment]
I followed the readme:

```
sylvainlap@CanHardXI:~/DEV/WORKSPACE$ strapi new test
/usr/bin/strapi: 2: /usr/bin/strapi: [[: not found
info: Your new application `test` is ready at `/home/sylvainlap/DEV/WORKSPACE/test`.
warn: You do not have a `.strapirc` file at `/home/sylvainlap`.
warn: First, you need to create an account on http://dashboard.strapi.io/
warn: Then, execute `$ strapi login` to start the experience.

sylvainlap@CanHardXI:~/DEV/WORKSPACE$ cd test/

sylvainlap@CanHardXI:~/DEV/WORKSPACE/test$ strapi start
/usr/bin/strapi: 2: /usr/bin/strapi: [[: not found
module.js:338
    throw err;
    ^
Error: Cannot find module '../Passport'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/sylvainlap/DEV/WORKSPACE/test/modules/user/api/services/protocols/oauth.js:8:25)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/sylvainlap/DEV/WORKSPACE/test/modules/user/api/services/protocols/index.js:4:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/sylvainlap/DEV/WORKSPACE/test/modules/user/api/services/passport.js:16:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

Do I have to do strapi login first ?

**Comment by sylvainlap** [comment]
Looks like oauth.js & oauth2.js need
```
const PassportService = require('../passport');
```
instead of
```
const PassportService = require('../Passport');
```

**Comment by loicsaintroch** [comment]
Thanks! Just fixed this bug (see https://github.com/wistityhq/strapi-generate-users/commit/84aefa9a1941a9623e364e1ab297872171cf3cb6) and publish `v1.0.2` of `strapi-generate-users`.

**Comment by sylvainlap** [comment]
I was making a pull request when I saw your commit ;)

**Comment by sylvainlap** [comment]
Looks like everything is working fine, but still have
    /usr/bin/strapi: 2: /usr/bin/strapi: [[: not found

**Comment by loicsaintroch** [comment]
Hey guys!

I came over to another solution. Can you try again:

```bash
$ [sudo] npm uninstall strapi -g
$ [sudo] npm cache clear
$ git clone -b fix/shebang git@github.com:wistityhq/strapi.git
$ cd strapi
$ npm link
```

and give me your feedback please?

**Comment by loicsaintroch** [comment]
It should be fixed: https://github.com/wistityhq/strapi/commit/968e36d87919dbb6a61365a0db8b34924975d5bd.

Can you try and give me your feedback please?

**Comment by sylvainlap** [comment]
OK for me. You can close it.

**Comment by loicsaintroch** [comment]
What about you @mocallu?

**Comment by mocallu** [comment]
Yes, it's working now. Thank you @loicsaintroch!

**Comment by loicsaintroch** [comment]
Perfect!
