### ISSUE TITLE
Error: Cannot find module 'validator' - Strapi 1.5.0 

### ISSUE THREAD

**Issue by kulakowka** [wistityhq/strapi#48]
I have updated the version of the library to 1.5.0.
I tried to create a new application and got an error:

```
~/Documents/node.js/sandbox » strapi version
1.5.0
~/Documents/node.js/sandbox » strapi new MyApp2
module.js:340
    throw err;
    ^

Error: Cannot find module 'validator'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/strapi/node_modules/anchor/index.js:6:16)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /usr/local/lib/node_modules/strapi/node_modules/strapi-generate-new/lib/after.js:74:15
    at /usr/local/lib/node_modules/strapi/node_modules/lodash/index.js:3073:15
    at baseForOwn (/usr/local/lib/node_modules/strapi/node_modules/lodash/index.js:2046:14)
    at /usr/local/lib/node_modules/strapi/node_modules/lodash/index.js:3043:18
    at Function.<anonymous> (/usr/local/lib/node_modules/strapi/node_modules/lodash/index.js:3346:13)
```

P.S. I really liked the new version of the studio.

**Comment by loicsaintroch** [comment]
Weird... Can you please try:

```bash
$ sudo npm uninstall strapi -g
$ sudo npm cache clean
$ sudo npm install strapi -g
```

**Comment by kulakowka** [comment]
Thank you. It helped me. 

```
~/Documents/node.js/sandbox » strapi new strapi_1.5.0_test
info: Your new application `strapi_1.5.0_test` is ready at `/Users/kulakowka/Documents/node.js/sandbox/strapi_1.5.0_test`.
```

I think you need to add this information to Readme.md.

**Comment by loicsaintroch** [comment]
Awesome! We'll probably add a `UPGRADING.md` file next week.
